# Configuration for running the SYS ouside a Docker
# Last update February 2023 (rlh)
server:
  port: 8540
  
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: acme-ui
  client:
    healthcheck:
      enabled: false # this must be false because is a UI
    registerWithEureka: true
    fetchRegistry: true       # this must be true because is UI
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registry-fetch-interval-seconds: 5

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

security:
  iam:
    provider-uri: http://localhost:8072/ailegorreta/iam-service       # use the gateway
    load-balanced: false

# Camunda BPM
camunda:
  tasklist:
    username: "{cipher}AQCfybuCs2Fl9fq35ohiKL11DSuuOnWWyBqV1MR6mcg0lfKuMreRiLz1znGSc5ImYCa3eM5ymOc7bhzSVifKB6I7ZWwOsh/WxvxtSacN4+zgMR9r6gZp1w2itnxMgqjNxYidL46gDQ3eCDdHyI8awf13Hs/fZdm81CDtWMElXn7QoiqMBnqp8MFsKelBdN6tnu+/TfIaDjvcxlQn++ey8y14Zd1dhmAa4nwUdoVmz44kX28FMGJWSXlsR1YHRvNxP4GaAgJ/qNJ01PUsN/Vjn2CE0ZTEP3h4NynocY3JUTsRDg4/eUTNojZCQKX1IEU/NurKq9S9xu5lEN7YizOeOQt03oXfNbQE/RTtd9b7vF8MSo8Jiqq7ROMIwQWvjN3U0kY="
    password: "{cipher}AQCfybuCs2Fl9fq35ohiKL11DSuuOnWWyBqV1MR6mcg0lfKuMreRiLz1znGSc5ImYCa3eM5ymOc7bhzSVifKB6I7ZWwOsh/WxvxtSacN4+zgMR9r6gZp1w2itnxMgqjNxYidL46gDQ3eCDdHyI8awf13Hs/fZdm81CDtWMElXn7QoiqMBnqp8MFsKelBdN6tnu+/TfIaDjvcxlQn++ey8y14Zd1dhmAa4nwUdoVmz44kX28FMGJWSXlsR1YHRvNxP4GaAgJ/qNJ01PUsN/Vjn2CE0ZTEP3h4NynocY3JUTsRDg4/eUTNojZCQKX1IEU/NurKq9S9xu5lEN7YizOeOQt03oXfNbQE/RTtd9b7vF8MSo8Jiqq7ROMIwQWvjN3U0kY="

# Alfresco content management server
alfresco:
  username: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="
  password: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="
