# Last update August 2023 (rlh)
server:
  port: 8300

spring:
  data:
    mongodb:
      username: "{cipher}AQA+A8PnaTRC5XMed08i9XAROYKHJmjm8eaQs9XQjeTnGo5UVCRzQPclKgoXVdhA/B8lcnLcofc1E42vX3FaQ0QavRxwrG9QI/SeerVzTLmT3r3NmyEOsQ2UHgwlAITRxlMqL+plcKkRJUD1/STO4PUPx4fNFl+SV93gDxaz39yOF/WPtKPr0RdLL4JNy6gws08rQ/Pg0NpUnIu1F/kz4qyq8NpDkgnyzMkXrGmHPghbvPVlASWKzsbodeWnrclI6/BBqZvFLjHwADxrHNG5EIQuCdLZMCnIdAu4XFwLUbcgOvz0ZVZJg3aVvkpLs0Tn7fuKno55MTSKdeNofwe73m7ljSRTgVg4GTnE4GX87VlmALPsxUgMugx3sdzmVnnQnE4="
      password: "{cipher}AQA1Qz/vJZWfGZ4Eeelivuk0rJHNXiuThLBS44dfKzX6BcluOyT9vF1FBs1Zlu3HhCj6NRxxaWnW5QvIQfWeH8sYP7TutaJ2lfx1BpJ4+1QSD9VP11I78+du3mP6HTpWtaHHX45YbPPiuCVBIPbbq6N3k3mXy9vu99rw/XpsDE6d8f3U8PAxaPz9r7zW3TXqbEeLw/Nq+Vfcc00zzfTz6Ki4HYKTPBWEvq78/mqUCaZ8wFHMPQwqeT3hy9RKHr157f3CSQEpBs4xCGohpjuTwoOOhxXlvymuvupmy986/jKUUhc7nR/INji7GhSy5F2t45GYs4tc+EyDspRLqADQt769AFUG7LADnKV2oaLmDXmRbZI5zCDAd1O+suQ0MU6gGYw="

# Testing what environment we are using
audit:
  greeting: "Welcome to audit microservice from the config server, 'default configuration'."