# Last update May 2023 (rlh)
server:
  port: 9000

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# Testing what environment we are using
auth:
  greeting: "Welcome to auth microservice from the config server, 'default configuration'."
