# Last update May 2023 (rlh)
server:
  port: 9000

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5452/authdb
    username: "{cipher}AQAwlsEKEoft5culvyzjD7uhF9k1xFFKHXAQkT6cVaVhqgo2Ls5/TVNNucJkK9NqPCf6UE6kXJ46o8IwGq/j00w87AJwbQEIN69tD5joIUWOA6mO0WBBYDIisMszlnExtQtFJ2FJUOk6C4tBQkzqnEHlKD4dOnZuHl2GLPF+TWzwz7060GxqYEwZ9keLyE60BEcaFPS9klPMB8KC6POy+8u7+xneJkPRHjeaAugqEIIjqIe0tGU0qjgI649JbuQvAGUVRNrLNTvby4uc3bUCtOn9E0IqWmls9TEFP2yULguF/rzW8bYpjOrknkh5oTLpS9UoEKe87i13PYAg8BphZ/pr0+JHQbVByefksjfq+OGck8xMzQz7d0lV8AHBce31Sv0="
    password: "{cipher}AQBTT7xm4Vpg6eBrLyAY+mBd1GVa2JrlmqdJJyw08iofFbFJIFC9gK5+j1Azwm+9cvqCEfW6L0KPzHJB9zfrr1w5FBarEGzz5C4EUdcfVGt47Wy73RsM6/u5BAY3/p2dGoxo0hvmwSYmTy9oT8574tU/mRjE0M6jipsQzpdByZOM33Z4C7To/xdXCK/IlUho+DVHFxsjQDHHMJes7CzXqSJAaT4c4Rn8zibVfN1/+337cWpZZzgMwXjueqTAErKj1IbTB/R35lmrdyHTq7SNA9yDd719Uhw3PdQBmr/qWwKYa3zwIsJMGYpLiDFhBYhb+WRiqv2Zwy5fpJlxqI+lpGhCii7lKPc4fVT0v4kuTPDRDqoK+Odxyv7N4X7EDmhwadc="
    hikari:
      connection-timeout: 2000  # The maximum time (ms) to spend waiting to get a connection from the pool
      maximum-pool-size: 5      # The maximum number of connections HikariCP will keep in the pool
  r2dbc:
    username: "{cipher}AQAwlsEKEoft5culvyzjD7uhF9k1xFFKHXAQkT6cVaVhqgo2Ls5/TVNNucJkK9NqPCf6UE6kXJ46o8IwGq/j00w87AJwbQEIN69tD5joIUWOA6mO0WBBYDIisMszlnExtQtFJ2FJUOk6C4tBQkzqnEHlKD4dOnZuHl2GLPF+TWzwz7060GxqYEwZ9keLyE60BEcaFPS9klPMB8KC6POy+8u7+xneJkPRHjeaAugqEIIjqIe0tGU0qjgI649JbuQvAGUVRNrLNTvby4uc3bUCtOn9E0IqWmls9TEFP2yULguF/rzW8bYpjOrknkh5oTLpS9UoEKe87i13PYAg8BphZ/pr0+JHQbVByefksjfq+OGck8xMzQz7d0lV8AHBce31Sv0="
    password: "{cipher}AQBTT7xm4Vpg6eBrLyAY+mBd1GVa2JrlmqdJJyw08iofFbFJIFC9gK5+j1Azwm+9cvqCEfW6L0KPzHJB9zfrr1w5FBarEGzz5C4EUdcfVGt47Wy73RsM6/u5BAY3/p2dGoxo0hvmwSYmTy9oT8574tU/mRjE0M6jipsQzpdByZOM33Z4C7To/xdXCK/IlUho+DVHFxsjQDHHMJes7CzXqSJAaT4c4Rn8zibVfN1/+337cWpZZzgMwXjueqTAErKj1IbTB/R35lmrdyHTq7SNA9yDd719Uhw3PdQBmr/qWwKYa3zwIsJMGYpLiDFhBYhb+WRiqv2Zwy5fpJlxqI+lpGhCii7lKPc4fVT0v4kuTPDRDqoK+Odxyv7N4X7EDmhwadc="
    url: r2dbc:postgresql://localhost:5452/authdb
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: "{cipher}AQCR/l9rTlQg+kr+6oPX2+ekiRayjct2ajZWKxf4ojkCUY6p8M7CmHylzJtE9Q9bIrnBhbt3PwbmmYLKmgS0aficZM2EpP6oztME8nNMPR3q63X0bJ6DQ8Ry/cu5cpr+Un4YHzYj6ea+tSsexyRS/UnjzoPYdapEPnl8g/1d/vee8FMRbCNWMxK3N6zl6Fj9r0s+xMghk6zRdROhLbaaBSnLEd+ofe/LyaxrSCW1nlkQyhowpmm0RiiSIljbKK7jL6beyCLfE21oOMb3lTk6ooa9FhkTb6AMmUrKOR0p1o2YyqIMVPLQau9WndouWUZocPXtDqkSAFngnZtluZhprmnJ7GAFVKtCIHT+fpbENM4cUhsQooPGpALlbcdi/cV7bH8="
      password: "{cipher}AQBsQvfeoBCcksFQo+AOCW2ZqHrROmgMOfvfgE8BzQvxhowKWXdxrSwoXHrLXtu839ufcQs0KxzMqa5dCoUbvnMQ/hjmCgBude0Ejo3pP+KMkRHpTBtb3qWR05FEMMNiS7LpOymhqpviuu0qGczjjKa8CeP+1thDmdjSsGKftoCyvmA2P8dEMkHKx4mVLxtWVduw70YX6c83QrjaSdEw+aZsxkS48IA9QtL1L4Q45o4i81qCbO0gmhiA3wIzNIklsA1sfD8kb377W+l9b66rLuIxMeltdJylvlajP33fDXxpLI37R7bMGtcSwy9WyQv8p/dKrjxI/xKD0231RGl81bUyfXp1pO0EuFZpfMoh2BZtGfZSpsg54pjjIkpa0kKwYrM="
  profiles:
    active: kubernetes

# Configuration properties for OpenLDAP: Docker image osixia/openldap
ailegorreta:
  ldap:
    uri: ldap://localhost:389
    adminuser: "{cipher}AQAJXgylo9chns8lBlSlV0uOReU7VTzcwjQ4cav78mbP0eYR2UzJ2t8TWLv9urN3Lx9otxnJ9aR7YfJnTI9+mvv4kV9uTf1vhyoyU15mOqbmHFJ1zL+qAO4AxVzpWlKB1WtiXXuk9OmgOnLOrgfBybVPJjiqvs6dVWfVNjRYycPvhCHlXSqlqF6JJiht5Rch0O8abdsui+YGbQ+x4noQsWK7NsaotemMCzSDUdws+SXmuiJZWzw0r2zgVHvv/L+TkMOnDVdwivLVV96pKhzFm10lFfrgYhTcMgC/dBn9yMiTZSbzMTnC3Zy22r6pREBfuHY94ltfWymzQI2lMG8B0IcuN7J6oeyOgwqJNL6x+1S60XsS+Cx59Wc8cwmXspOHCXWAp+H0an4ZvdhfrgyyGIJQ"
    credentials: "{cipher}AQAgG0wual5s3pgp+SOBRjJkDda8G9PKdg+9+u2ujr+F/JpE9EBahJ4/dpkO1uhMj3OpVJLgsc16T1DnipEo3E6B6AKLSt76YnwXnWwPT4a4GmiAaCf6coa5xQQJI4wnZPlrYDQ9h8BdRuKQgjAD4gtmFkwfYKBzB6j4k1vdGer/gO5VPFgCZycL+Qi0VD6l7mZnrr7LoTrPDoxWIjqKp6bwhBblr/cvADZdW8PBX5VF2oBT6/iX++jgnqqftPCaRKpqiNnVZl6NyMQHMpahKurqrMEH0RsgQmAazOWwCo8TVpNBbBW2dDXPdLbI+aQPdISLsAo8ZwrgU6HH1BOeiWGNGqsiQgmFQZMk7oso+9l+We1q2l1ciL70SVgXQh1l5qk="
  neo4j:
    flyway:
      locations: /db/neo4j/migration # Script to initialize iamDB


# Testing what environment we are using
auth:
  greeting: "Welcome to auth microservice from the config server, 'default configuration'."
