# Last update February 2024 (rlh)
server:
  port: 8541

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: bup-bulk-service
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      kafka:
        binder:
          brokers: http://localhost:9092

# Back-end microservices
microservice:
  bup:
    provider-uri: http://glocalhost:8072/bup-service        # use the gateway (or 'bup' url is ok)
    # provider-uri: http://localhost:8520  # warn: it uses load balanced

# Testing what environment we are using
bup-bulk-service:
  greeting: "Welcome to bup-bulk-service microservice from the config server, 'local configuration'."
