# Docker desktop localNoDocker configuration
# Last update February 2023 (rlh)
server:
  port: 8351

eureka:
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

#Back-end microservices
microservice:
  param:
    provider-uri: http://localhost:8072/param       # use the gateway
    # provider-uri: http://localhost:8350             # no use gateway, because is backoffice microservice communication
    # we prefer to skip the gateway. Depends on system security

#Redis database
redis:
  server: localhost
  port: 6379
