# Last update July 2023 (rlh)

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      kafka:
        binder:
          brokers: http://kafka:9092

#Redis database
redis:
  server: redis
  port: 6379

# Testing what environment we are using
cache:
  greeting: "Welcome to cache microservice from the config server, 'default configuration'."
