# Last update April 2025 (rlh)
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: cartera-service
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1415;databaseName=master
  flyway:
    uri: jdbc:sqlserver://localhost:1415;databaseName=master

# Testing what environment we are using
param:
  greeting: "Welcome to cartera-service microservice from the config server, 'localNoDocker configuration'."