# Last update July 2023
server:
  port: 8070

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# value used for AWS, here can be anything
eureka:
  environment: ${spring.profiles.active}
  # Testing what environment we are using
  greeting: "Welcome to eureka microservice from the config server, 'local configuration'."