# Last update May 2023 (rlh)

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: expediente
  client:
    enabled: false              # Not used, just for Docker desktop with service discovery and load balanced
    registerWithEureka: true
    fetchRegistry: false        # this must be false because it is a service

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# This is the permit where all auditory events are notified
expediente:
  greeting: "Welcome to expediente microservice from the config server, 'default configuration'."
  notifica:
    facultad: NOTIFICA_DOC
  

