# Last update May 2023 (rlh)

spring:
  cloud:
    gateway:
      # This is if we want manually mapping routing using service discovery
      # Erase al postfix for '-service' microservices
      routes:
      - id: iam-service
        uri: lb://iam
        predicates:
        - Path=/iam-service/**
        filters:
        - RewritePath=/iam-service/(?<path>.*), /$\{path}
      - id: udf-service
        uri: lb://udf
        predicates:
        - Path=/udf-service/**
        filters:
        - RewritePath=/udf-service/(?<path>.*), /$\{path}
      - id: preference-service
        uri: lb://preference
        predicates:
          - Path=/preference-service/**
        filters:
          - RewritePath=/preference-service/(?<path>.*), /$\{path}
      - id: audit-service
        uri: lb://audit
        predicates:
          - Path=/audit-service/**
        filters:
          - RewritePath=/audit-service/(?<path>.*), /$\{path}
      - id: cache-service
        uri: lb://cache
        predicates:
          - Path=/cache-service/**
        filters:
          - RewritePath=/cache-service/(?<path>.*), /$\{path}
      - id: bup-service
        uri: lb://bup
        predicates:
          - Path=/bup-service/**
        filters:
          - RewritePath=/bup-service/(?<path>.*), /$\{path}
      - id: cartera-service
        uri: lb://cartera
        predicates:
          - Path=/cartera-service/**
        filters:
          - RewritePath=/cartera-service/(?<path>.*), /$\{path}
      - id: expediente-service
        uri: lb://expediente
        predicates:
          - Path=/expediente-service/**
        filters:
          - RewritePath=/expediente-service/(?<path>.*), /$\{path}
      - id: mail-service
        uri: lb://mail
        predicates:
          - Path=/mail-service/**
        filters:
          - RewritePath=/mail-service/(?<path>.*), /$\{path}
      - id: order-service
        uri: lb://order
        predicates:
          - Path=/order-service/**
        filters:
          - RewritePath=/order-service/(?<path>.*), /$\{path}
      - id: param-service
        uri: lb://param
        predicates:
          - Path=/param-service/**
        filters:
          - RewritePath=/param-service/(?<path>.*), /$\{path}
      - id: test-service                                        # The route ID
        uri: ${TEST_SERVICE_URL:http://127.0.0.1:8000}
        predicates:
          - Path=/test/**                                       # The predicate is a path to match
        filters:
          - RewritePath=/test/(?<path>.*), /$\{path}-service    # Rewrite the path to include the 'service'
          - name: CircuitBreaker                                # Filter name for Circuit breaker
            args:
              name: testCircuitBreaker                          # Name of the circuit breaker
              fallbackUri: forward:/test-service-fallback       # Forwards request to this URI when the circuit is open

# Testing what environment we are using
gateway:
  greeting: "Welcome to gateway microservice from the config server, 'default configuration'."

