# Docker desktop local configuration
# Last update February 2023 (rlh)
server:
  port: 8180

eureka:
  client:
    healthcheck:
      enabled: true     # this must be true because it is a service
    serviceUrl:
      defaultZone: http://eureka:8070/eureka/

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://kafka:9092

  # Neo4j encrypted data
  neo4j:
    uri: bolt://neo4jDB:7687
    authentication:
      username: "{cipher}AQAJb5LYVo60uJkQ8PgyiqeJggrXtB93DGqBE2VvhE3B3/WI30pUn4jzsDjNGSkEE3lPxdXa4d6lJbUJn94ISEwXy+myn+K/ETpT6EIxRZb1i1C8y/Fqqm+jEipxpKfX70Ed1zfUS4cR4z9anZiqvoyLSX0r6n0G1YUeOPfjkXWJ9VJaYq3738dDH4AkodRDp5I8Q41vUCUnqSUa8Ol+nvAHMD5olYgcAT8Bp/qWYLJi2BQEgQ3XRG2d6ZjaF6nVnVhafIFxylBJDmId4cW6mZ2M1MXmFWaSuJua1RI9/kpzCFeZ7lz09pF6zAvHzTPzoD3WJbtCVIM6Uyfe+fPlacVg/5CcmhJYXhwTnCGZT/oYAlq0HCYb6hfs83iz1F7Z07o="
      password: "{cipher}AQBbi+saQ0gNEDCLWmesHdf51ki4vI2Ee//T6y0d/FdsuPzSaix48d+Xdkjpy5lwbRd2bc7Rnn0Lws64IvMOsL/70IM+bE9LIJJUPMSIc7Qu677qx6CdiP+fwdwTpoOJ9fJDLeOYctgfvHPu9olWGM6xKqKZ41J3U7fi2M0Z40WpoP8uEwSJ00Vi8IFN64iJ2TeEf0Sz8DuFcS0z6WQDNoHNxhfVEsaV1+g4z0v9XsWogXgnP+0/mtsiartaC5NFlDESs7juZ4mZDw3qpUAKxUFVabp2zJBEZe1wyconBGG6sd0AjHy+/L4JLDhqPZmu1CqX8bssy8XGuuSoBrTLYn54Lu62QQbzuPR/YglRQLaJVnlShg8x0WQpR9QfPy2wNfA="

management:
  tracing:
    sampling:
      probability: 0.1 # only for production, switch back to 1.0 for development
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
