# Last update June 2023 (rlh)
server:
  port: 8180

# Eureka is just for docker-compose container
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: iam-service
  client:
    healthcheck:
      enabled: true     # this must be true because it is a service
    serviceUrl:
      defaultZone: http://eureka-service:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  neo4j:
    repositories:
      type: imperative
    uri: bolt://localhost:7687
    authentication:
      username: "{cipher}AQBYbOSFhaIbuqC61IeovSE0G+p4CTpOEQmMtBAU/iTWFTemVPaaD1UV63G3tylq629LRW4EkOr4g8iqfYj8+TNMQeopFLl/QR0m+O16TeTz4u01vh2Lp/oXNcp1Usne20pu5VhjrjWvIc9o3rR5PLBOAnfSY5vPhz6cLBiSLjYPiDDHdreso055xEThRVsCbaOAxg75eRHC9EbBDAaQfAxcB36PCsnFeVdW3LO7s62Uw1LX7QKmTT4jyq61f1ghu/ldMbeJHzPf7SN8KOh6DGXPgLNzvqEboGxYSZ8hQ7sUDhCLeDQksqtAny8MCNUGMqIY2QVU+qsdQaMzfo7aMt4nnMOO/PkA0Mc9r8/G7U5j8SdKsLXvfEs8ywojj6jsUlo="
      password: "{cipher}AQBEKaVUSx+jvYXrbjH3POQlsSvz95ZeevxlQ6ZUxSsMi66/P5wbYM8Y4qKqNe/EanNN+HGqHqQKXSRQUSJsPe5avFKROGxw09qcyLEw3CMaVW/IgvtJp2NUMcemgmQxc7K5V+rWkYo6qyU/hV3RoFfSbNCl6WgputPUG33tTslcYJlrV+IPHuVC9TG8VtsYFFfldW/W7OqdxQUDKYfd79ASSzMS4HHpLMkFUiRLCULrV7ooDCKvYmcHmYU3qWGXtNjb14lKm9djGr9OPxQG827vnY4BdIUaYfffHFv0EB6e9DhwnyFziFOh6Umii412Ri4krP6atZQASWaWBkzyo33gdi9TUAwc9oFfPsSXNMykBC+JbLbhfkC9rl7tsf3Qvbw="

# Testing what environment we are using
iam:
  greeting: "Welcome to iam microservice from the config server, 'local configuration'."