# Configuration for running the iam-ui inside a Docker desktop local.
# Last update September 2023 (rlh)
server:
  port: 8190
  
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: iam-ui
  client:
    healthcheck:
      enabled: false # this must be false because is a UI
    registerWithEureka: true
    fetchRegistry: true       # this must be true because is UI
    serviceUrl:
      defaultZone: http://eureka:8070/eureka/
    registry-fetch-interval-seconds: 5

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

security:
  iam:
    provider-uri: http://gateway:8072/iam       # use the gateway
    load-balanced: true                         # in docker we use load balanced webClient instance

#Back-end microservices
microservice:
  cache:
    provider-uri: http://gateway:8072/cache           # use the gateway
    # provider-uri: http://cache:8351                 # do not use gateway
  audit:
    provider-uri: http://gateway:8072/audit-service   # use the gateway
    #provider-uri: http://audit:8300                  # do not use gateway
    subscription:
      host: audit                                     # note: we do not use gateway
      port: 8301
  iam:
    provider-uri: http://gateway:8072/iam   # use the gateway
    # provider-uri: http://iam:8180         # no use gateway, because is backoffice microservice communication
    # we prefer to skip the gateway. Depends on system security

