# Last update June 2023 (rlh)

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      kafka:
        binder:
          brokers: http://kafka:9092

ailegorreta:
  neo4j:
    flyway:
      locations: /db/neo4j/migration # Script to initialize iamDB (also in auth-service)

iam:
  greeting: "Welcome to iam microservice from the config server, 'default configuration'."
  # This is the permit where all auditory events are notified
  notifica:
    facultad: NOTIFICA_IAM

