# Last update October 2023(rlh)
server:
  port: 8352

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: mail-service
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://eureka-service:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  mail:
    password: "{cipher}AQBFW0MGYlSQrxM4bQxrvmSjIe4sXBXNPFrJZ/6cQlmXKV+UePAN/gP2UjoQXZF3zEpbMkM2OPMdQvjHjbHhixNXkRXBDB6E7yQ0vtPVsHTaBQIBWTlEdXMFzyqGImX9rAdCd3ARAHK18353EQp4yGrmCVocQVVJPTLy5lPhGwfHwMQ41Qk6bZMnOF4RAbV35NAbUFs0x+jLARwh0u6ywx95vz7g3Y0BDi19vison+gKNvKmZEzZeVNoD2a1Sl5gGOBp/wZ80ge1yb9ahJSf0KTZngEI/8hWS9mkp2vEBvguTMS6sKoPvt/kVl/zoTjJm7nNRh0Mb06/jDhuRjhrMwhFLbfrOlNzCfsMKPEv3CGTW+oSD8ZxJQS2Uq+khBTjD2s="


# Alfresco content management server
alfresco:
  username: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="
  password: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="

# Testing what environment we are using
mail:
  greeting: "Welcome to mail microservice from the config server, 'local configuration'."