# Last update October 2023(rlh)
server:
  port: 8352

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: mail-service
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://eureka-service:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  cloud:
    config:
      uri: http://config-server:8071
  mail:
    password: "{cipher}AQAp8cRpPLunAgqM5HOV9HqvFa2CXR+zAVo9BtM+dku1Mr4Bu7n2+6H6fGghs1wbzr9/DAy9gFfMEMqbfw95n2Gpjfhk3CDqkdLjka40VbiIskxIVDwmu2/yOzQaLJpgjPNJXGJETxwKvWezGkLx62wohVPlSOyrGy1OZAhxgwDlAm2x4HzhGeCxERhTCJqytHa39H6EfLIJU+M0m84mZ6I6hKZczjHMgGym79UjQYjhLhKrUlyPd5cDkDrAPIC/RWru8tkfHe/ejO4yPxQ1dCVx7TgSFRE86TawWsP4d6S0cTaGGKIVXTwKXMkqKgrVnu5gQSjz0Ij+ftZTVvikJLxVuf/JPWNWHq3l8+dRV99K+UH84HyNwWU2qwNStjaRbTg="


# Alfresco content management server
alfresco:
  username: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="
  password: "{cipher}AQBkhkMP17tx3NdMPQJ4ErenK9WyWvIxrPuJegMZPX+Z2MnYeOVAmrsbh8vfSTehjOyhoxqE8yeQafOPJeqhI9aLHTwwo3FTCrZQrGnxHbUTCXWvypp7DwH3DIqhNzMgYoDMjArMibiIqHASMH9de3PW70/u+nHBXFeDZsbRnBoBuTzFtunrI+RlU0bmgzV1/R+cdTG720ttMnFWVGGfKNxuPpLoGTnXtsvoS0lF28183FUv/LS/FSdlz1j5cy6ypLGB/TEMAtScXA+0zqulE0o2uulxGLdoKFZ3ifXnR7ZVn9zCnwtt5CWfc7Yc3iwNJottC7XWvjT6ARhQB8vr9IBTsVXcZrX8PDC3jvcHHzUAQpos72dDBFb8pQ1PmVzo27o="

# Testing what environment we are using
mail:
  greeting: "Welcome to mail microservice from the config server, 'local configuration'."