# Last update November 2023 (rlh)
server:
  port: 8530

# Eureka is just for docker-compose container
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: order-service
  client:
    healthcheck:
      enabled: true     # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  cloud:
    config:
      uri: http://config-server:8071

# Testing what environment we are using
order:
  greeting: "Welcome to order microservice from the config server, 'local configuration'."