# Last update May 2023 (rlh)

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: order
  client:
    enabled: false              # Not used, just for Docker desktop with service discovery and load balanced
    registerWithEureka: true
    fetchRegistry: false        # this must be false because it is a service

spring:
  neo4j:
    repositories:
      type: imperative
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  
# Testing what environment we are using
order:
  greeting: "Welcome to order microservice from the config server, 'default configuration'."
