# Docker desktop localNoDocker configuration
# Last update March 2023 (rlh)
server:
  port: 8183

eureka:
  client:
    healthcheck:
      enabled: true     # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  # Neo4j encrypted data
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: "{cipher}AQAJb5LYVo60uJkQ8PgyiqeJggrXtB93DGqBE2VvhE3B3/WI30pUn4jzsDjNGSkEE3lPxdXa4d6lJbUJn94ISEwXy+myn+K/ETpT6EIxRZb1i1C8y/Fqqm+jEipxpKfX70Ed1zfUS4cR4z9anZiqvoyLSX0r6n0G1YUeOPfjkXWJ9VJaYq3738dDH4AkodRDp5I8Q41vUCUnqSUa8Ol+nvAHMD5olYgcAT8Bp/qWYLJi2BQEgQ3XRG2d6ZjaF6nVnVhafIFxylBJDmId4cW6mZ2M1MXmFWaSuJua1RI9/kpzCFeZ7lz09pF6zAvHzTPzoD3WJbtCVIM6Uyfe+fPlacVg/5CcmhJYXhwTnCGZT/oYAlq0HCYb6hfs83iz1F7Z07o="
      password: "{cipher}AQBbi+saQ0gNEDCLWmesHdf51ki4vI2Ee//T6y0d/FdsuPzSaix48d+Xdkjpy5lwbRd2bc7Rnn0Lws64IvMOsL/70IM+bE9LIJJUPMSIc7Qu677qx6CdiP+fwdwTpoOJ9fJDLeOYctgfvHPu9olWGM6xKqKZ41J3U7fi2M0Z40WpoP8uEwSJ00Vi8IFN64iJ2TeEf0Sz8DuFcS0z6WQDNoHNxhfVEsaV1+g4z0v9XsWogXgnP+0/mtsiartaC5NFlDESs7juZ4mZDw3qpUAKxUFVabp2zJBEZe1wyconBGG6sd0AjHy+/L4JLDhqPZmu1CqX8bssy8XGuuSoBrTLYn54Lu62QQbzuPR/YglRQLaJVnlShg8x0WQpR9QfPy2wNfA="
  
management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Testing what environment we are using
preference:
  greeting: "Welcome to preference microservice from the config server, 'localNoDocker configuration'."