# Docker desktop localNoDocker configuration
# Last update February 2023 (rlh)
server:
  port: 8200

eureka:
  client:
    healthcheck:
      enabled: true     # this must be true because it is a service
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: http://kafka:9092
  # SQL Server encrypted data. Data base udfDB
  datasource:
    url: jdbc:postgresql://localhost:5452/udfdb
    username: "{cipher}AQA2GH4NpK1oG5cAR2xOzdpZtJ3jTaYJygcPv+ZOqqJaoi8ymBRHiI+EfEWcS4LBirBENx/XChKYypZCDnOKt7a9KQ8GGsrFiN7rTP6ZTZlfKCQFGPA4axavSUcLoZW0RoclrrpEsg0qAVEyCpfUKGKMzov5JGBuJCKy9ahW5kM29Bz40gZHsVbWMVwBUBtCOy8PTIiwVXV8oxm7xkyh0BOiIlNXXtqYyZLrkRaD057Btufpsgxi7Rywyrw4KN9qIaYR004JRYcWrQj9Ef9upP0LgL7vdWZV1S6BNJnVM42gFQf8v3yKa1zPMiJ5yNqADClRHqRwtxx/rUjjStg8jSMILSWklGwwptCdxvpx6tvUneKMfQTnuEZveqBHlC2JhIk="
    password: "{cipher}AQAVK1RrA8s6iiKBYWaygWGc1GwyI95aRts2aoO6Y1swxEbApjEvG02TNJadbRX3R/mkKzV+zmc19G0wZM70RQMTtvSV9aC6pQtuM6QiI2inBA5VOs5N+Kkr4DYUkhfb8WnZdtsr/SMFY3/S3HiFAnoNROgCdVSjyoGQa+VTY+ffGYNDWpw29xR4munA57hp6LtgTp6rINKXXNXKHWbd8GY3UKdyEKifc9Tm9jnzaCfrzEmhX1fK0/uNkTgssRtUj3lxz8ZSlkjDS+EHcq9qGWIYdzKewRwJT/YLPNytEL/YGeu0tu9DN2gioyBmCEzy+t7D2OK1nfLUGGmeNQic9H5KnmXmyVmNWnVkK44nJPsJG70N295ewg9ZOTsVnsTqQGk="
    hikari:
      connection-timeout: 2000  # The maximum time (ms) to spend waiting to get a connection from the pool
      maximum-pool-size: 5      # The maximum number of connections HikariCP will keep in the poo

management:
  tracing:
    sampling:
      probability: 1.0 # only for testing purpose, switch back to 0.1 for production code
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Testing what environment we are using
udf:
  greeting: "Welcome to udf microservice from the config server, 'localNoDocker configuration'."